### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'

### ISSUE THREAD

**Issue by sultanoid** [tuanct1997/Federated-Learning-ASR-based-on-wav2vec-2.0#7]
Hello, I am getting the error, _pickle.UnpicklingError: invalid load key, 'v'. The full exception is as follows: 

```
Traceback (most recent call last):
  File "fl_w2v.py", line 544, in <module>
    pre_trained = pre_trained_point(args.pre_train_model_path,args.output,args.config_path, args.running_type, args.parallel_backend)
  File "fl_w2v.py", line 495, in pre_trained_point
    state_dict = torch.load(path)
  File "C:\Users\il66977\Desktop\PhD\Summer 2023\Project\Federated-Learning-ASR-based-on-wav2vec-2.0\venv\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\il66977\Desktop\PhD\Summer 2023\Project\Federated-Learning-ASR-based-on-wav2vec-2.0\venv\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by seuganger** [comment]
i'm facing the same error when using torch.load().have u solved it?

**Comment by sultanoid** [comment]
I have not solved it yet.

**Comment by tuanct1997** [comment]
Hi all, 

The problem you mentioned is due to the large file store on GitHub. If you want to pull the pre-trained model, you should use `git lfs pull` instead. 

I will soon provide a better way to store the pre-trained model instead of here on GitHub (maybe Drive).

**Comment by tuanct1997** [comment]
I will close the issue due to inactive
